// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";

export type ExecCommandApprovalParams = { conversation_id: ConversationId, 
/**
 * Use to correlate this with [codex_core::protocol::ExecCommandBeginEvent]
 * and [codex_core::protocol::ExecCommandEndEvent].
 */
call_id: string, command: Array<string>, cwd: string, reason: string | null, };
