// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/* eslint-disable @typescript-eslint/no-empty-object-type */

export type LoginApiKeyResponse = {};
