// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitWindow } from "./RateLimitWindow";

/**
 * Collection of rate limit windows for the current account.
 */
export interface RateLimitSnapshot {
  /**
   * Primary rate limit window (usually per-short-period quota).
   */
  primary?: RateLimitWindow;
  /**
   * Secondary rate limit window (longer duration quota).
   */
  secondary?: RateLimitWindow;
}
