// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthStatusChangeNotification } from "./AuthStatusChangeNotification";
import type { LoginChatGptCompleteNotification } from "./LoginChatGptCompleteNotification";

export type ServerNotification = { "type": "auth_status_change", "data": AuthStatusChangeNotification } | { "type": "login_chat_gpt_complete", "data": LoginChatGptCompleteNotification };
