(Π_STATE
  (time "2026-04-15T17:05:16Z")
  (branch "pi/fork-tax/2026-04-15-170411")
  (pre_head a0e67fbdfc2a)
  (dirty true)
  (checks
    (check (status skipped) (command "No fresh test run during fork-tax; see receipts.log for prior builds/tests"))
  )
  (repo_notes
    (upstream "git@github.com:riatzukiza/devel.git")
    (status_digest c40d1d334fc3c6aa)
    (note "Fork-tax snapshot branch created while workspace is dirty: 18 modified entries, 299 deletions.")
    (note "Proxx submodule HEAD pushed to origin; superproject may bump gitlink to match proxx HEAD in Π commit.")
    (note "See .ημ/Π_STATUS_2026-04-15_170516.txt for raw status + gitlink list; .gitmodules is known inconsistent with gitlinks (e.g., .ημ/03_ARTIFACTS/narrative_audio).")
    (submodule (path "orgs/open-hax/proxx") (head 668838793ad0) (branch "fix/ollama-cloud-glm-routing"))
    (changed_file ".ημ/Π_STATUS_2026-04-15_170516.txt")
    (changed_file ".ημ/REPO_STATE_HASH")
    (changed_file ".ημ/Π_LAST.md")
    (changed_file ".ημ/Π_MANIFEST.sha256")
    (changed_file ".ημ/Π_STATE.sexp")
    (changed_file "receipts.log")
    (changed_file "services/proxx/docker-compose.yml")
    (changed_file "services/openplanner/docker-compose.yml")
    (changed_file "services/openplanner/scripts/atlas-init.sh")
    (changed_file "orgs/open-hax/proxx")
  )
)
