/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as REDACTED_SECRETRoute } from './routes/__REDACTED_SECRET'
import { Route as SettingsImport } from './routes/settings'
import { Route as IndexImport } from './routes/index'
import { Route as CChatIdImport } from './routes/c.$chatId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => REDACTED_SECRETRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => REDACTED_SECRETRoute,
} as any)

const CChatIdRoute = CChatIdImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => REDACTED_SECRETRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof REDACTED_SECRETRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof REDACTED_SECRETRoute
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdImport
      parentRoute: typeof REDACTED_SECRETRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRoutesById {
  __REDACTED_SECRET__: typeof REDACTED_SECRETRoute
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/c/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/c/$chatId'
  id: '__REDACTED_SECRET__' | '/' | '/settings' | '/c/$chatId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CChatIdRoute: typeof CChatIdRoute
}

const REDACTED_SECRETRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CChatIdRoute: CChatIdRoute,
}

export const routeTree = REDACTED_SECRETRoute
  ._addFileChildren(REDACTED_SECRETRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__REDACTED_SECRET__": {
      "filePath": "__REDACTED_SECRET.tsx",
      "children": [
        "/",
        "/settings",
        "/c/$chatId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/c/$chatId": {
      "filePath": "c.$chatId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
